---
deployment:
  task:
    - export  DEPLOYPATH=/home/beskerte/public_html/
    - /bin/cp  -R fonts $DEPLOYPATH
    - /bin/cp  -R images $DEPLOYPATH
    - /bin/cp  -R js $DEPLOYPATH
    - /bin/cp  -R scss $DEPLOYPATH
    - /bin/cp  -R css $DEPLOYPATH
    - /bin/cp contact.php $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
